/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */
plugins {
    java
    application
    id("io.freefair.lombok") version "9.2.0"
    id("com.gradleup.shadow") version "9.4.0"
}

group = "io.canvasmc.discord"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    maven("https://repo.jsinco.dev/releases")
    maven("https://repo.okaeri.cloud/releases")
}

dependencies {
    // discord
    implementation("net.dv8tion:JDA:5.0.0-beta.24") {
        exclude("org.slf4j", "slf4j-api")
    }
    implementation("dev.jsinco.discord:jda-framework:1.8")

    // logger
    implementation("org.apache.logging.log4j:log4j-core:2.24.1")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.24.1")
    implementation("org.apache.logging.log4j:log4j-api:2.24.1")

    // Config
    implementation("eu.okaeri:okaeri-configs-yaml-snakeyaml:5.0.5")

    implementation("org.jspecify:jspecify:1.0.0")
}

application {
    mainClass.set("io.canvasmc.discord.Main")
}


tasks {
    shadowJar {
        dependencies {
            // Just include everything, standalone application.
        }
        archiveVersion.set("")
        archiveClassifier.set("")
    }

    jar {
        enabled = false // shadow
    }

    build {
        dependsOn(shadowJar)
    }
}